# Generated by Django 5.2.9 on 2026-02-22 10:28

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_attachment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
