# Generated by Django 5.2.9 on 2026-02-22 10:30

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='draft',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
