# Generated by Django 5.2.9 on 2026-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_attachment_name_alter_draft_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='encrypted_room_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
