# Generated by Django 5.2.9 on 2026-02-23 11:23

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_message_content_hash_message_iv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestatus',
            name='status',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано')], default='sent'),
        ),
    ]
