# Generated by Django 5.2.9 on 2026-02-21 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text='Уникальный идентификатор пользователя Telegram', unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, help_text='Telegram-имя пользователя', max_length=255, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя из Telegram', max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя из Telegram', max_length=255, null=True, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'indexes': [models.Index(fields=['telegram_id'], name='telegram_te_telegra_000672_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Bot', max_length=100, verbose_name='Название конфигурации')),
                ('bot_token', models.CharField(max_length=255, verbose_name='Токен Telegram-бота')),
                ('use_redis', models.BooleanField(default=False, help_text='Использовать RedisStorage')),
                ('redis_host', models.CharField(blank=True, help_text='Хост Redis', max_length=100, null=True)),
                ('redis_port', models.IntegerField(blank=True, help_text='Порт Redis', null=True)),
                ('redis_pass', models.CharField(blank=True, help_text='Пароль Redis', max_length=100, null=True)),
                ('other_params', models.TextField(blank=True, help_text='Дополнительные параметры (необязательно)', null=True)),
                ('channel_url', models.URLField(default='https://t.me/telegram', max_length=255, verbose_name='Ссылка на канал (для кнопки «Подписаться»)')),
                ('channel_id', models.CharField(default='-1001005640892', max_length=255, validators=[django.core.validators.RegexValidator(message='Укажи -100... (ID канала) или @username/username (5–32 символа, латиница/цифры/_).', regex='^(-100\\d+|@?[A-Za-z0-9_]{5,32})$')], verbose_name='Идентификатор канала (для проверки подписки)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Рекомендуется держать активной только одну конфигурацию.', verbose_name='Использовать эту конфигурацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('admins', models.ManyToManyField(blank=True, related_name='bots', to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Конфигурация Telegram-бота',
                'verbose_name_plural': 'Конфигурации Telegram-бота',
                'indexes': [models.Index(fields=['is_active'], name='telegram_bo_is_acti_288781_idx')],
            },
        ),
    ]
