"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from email.utils import parseaddr
import os
from pathlib import Path

import environ


env = environ.Env(
    DEBUG=(bool, False),

    # Internationalization
    LANGUAGE_CODE=(str, "ru-ru"),
    TIME_ZONE=(str, "Europe/Moscow"),
    USE_I18N=(bool, True),
    USE_TZ=(bool, True),

    # JWT Settings
    JWT_ACCESS_TOKEN_MINUTES=(int, 15),
    JWT_REFRESH_TOKEN_DAYS=(int, 1),
    JWT_SLIDING_TOKEN_MINUTES=(int, 30),
    JWT_SLIDING_REFRESH_DAYS=(int, 1),
    JWT_ALGORITHM=(str, "HS256"),
    JWT_AUTH_COOKIE=(str, "access_token"),
    JWT_AUTH_COOKIE_REFRESH=(str, "refresh"),
    JWT_AUTH_COOKIE_DOMAIN=(str, ".localhost"),
    JWT_AUTH_COOKIE_SECURE=(bool, True),
    JWT_AUTH_COOKIE_HTTP_ONLY=(bool, True),
    JWT_AUTH_COOKIE_SAMESITE=(str, "Lax"),
    JWT_AUTH_COOKIE_PATH=(str, "/"),
    JWT_ROTATE_REFRESH_TOKENS=(bool, True),
    JWT_BLACKLIST_AFTER_ROTATION=(bool, True),
    JWT_UPDATE_LAST_LOGIN=(bool, True),
    JWT_AUTH_HEADER_TYPES=(str, "Bearer"),
    JWT_AUTH_HEADER_NAME=(str, "HTTP_AUTHORIZATION"),
    JWT_USER_ID_FIELD=(str, "telegram_id"),
    JWT_USER_ID_CLAIM=(str, "telegram_id"),
    JWT_SLIDING_TOKEN_REFRESH_EXP_CLAIM=(str, "refresh_exp"),

    # CSRF
    CSRF_COOKIE_HTTPONLY=(bool, True),
    CSRF_COOKIE_SECURE=(bool, True),
    CSRF_USE_SESSIONS=(bool, True),
    CSRF_COOKIE_SAMESITE=(str, "Lax"),

    # SESSION
    SESSION_COOKIE_SECURE=(bool, True),
    SESSION_COOKIE_SAMESITE=(str, "Lax"),
    SESSION_COOKIE_DOMAIN=(str, ".localhost"),

    # CELERY
    CELERY_TASK_TRACK_STARTED=(bool, True),
    CELERY_TASK_TIME_LIMIT=(int, 30 * 60),

    # Data upload max limit
    DATA_UPLOAD_MAX_NUMBER_FIELDS=(int, 100000),

    # Extra settings
    CORS_ALLOW_CREDENTIALS=(bool, True),
    DJOSER_SEND_ACTIVATION_EMAIL=(bool, True),

    # Telegram WebHook
    WEB_SERVER_HOST=(str, "0.0.0.0"),
    WEB_SERVER_PORT=(int, 8080),
    WEBHOOK_PATH=(str, "/telegram"),
    WEBHOOK_SECRET=(str, "your-telegram-webhook-secret"),
    BASE_WEBHOOK_URL=(str, "https://webhook.localhost"),
    WEBHOOK_SSL_CERT=(str, "/etc/certificates/localhost.full.crt"),
    WEBHOOK_SSL_PRIV=(str, "/etc/certificates/localhost.key"),

    # 123
    FIELD_ENCRYPTION_KEY=(str, "your-encryption-key"),
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env.production'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Root domain via Sites framework
PROJECT_NAME = env("PROJECT_NAME", default="Default Project")
SITE_DOMAIN = env("SITE_DOMAIN", default="localhost")
STORAGE_DOMAIN = env("STORAGE_DOMAIN", default="static.localhost")
MEDIA_DOMAIN = env("MEDIA_DOMAIN", default="media.localhost")


# Allowed hosts
# See https://docs.djangoproject.com/en/6.0/ref/settings/#allowed-hosts

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])


# Application definition
WEBSOCKET_APPS = [
    'daphne',
    'channels',
]

THIRD_PARTY_APPS = [
    'celery',
    'django_celery_beat',
    'django_hosts',
    'django_filters',
    'encrypted_model_fields',
    'django_prometheus',
]

REST_API_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',
]

MAIN_APPS = [
    'telegram.apps.TelegramConfig',
    'api.apps.ApiConfig',
    'account.apps.AccountConfig',
    'messenger.apps.MessengerConfig',
    'sms_provider.apps.SmsProviderConfig',
    'video_call.apps.VideoCallConfig',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

INSTALLED_APPS += MAIN_APPS
INSTALLED_APPS += REST_API_APPS
INSTALLED_APPS += THIRD_PARTY_APPS

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',  # первым
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',  # последним
]

ROOT_URLCONF = 'backend.urls'
ROOT_HOSTCONF = 'backend.hosts'
DEFAULT_HOST = "www"
PARENT_HOST = SITE_DOMAIN


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Media file support
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = "backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL')
}

# Channel
# https://channels.readthedocs.io/en/stable/tutorial/part_2.html

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}


# Cache
# https://docs.djangoproject.com/en/6.0/topics/cache/

CACHES = {
    "default": env.cache("CACHE_URL", default="redis://redis:6379/0")
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE")

TIME_ZONE = env("TIME_ZONE")

USE_I18N = env("USE_I18N")

USE_TZ = env("USE_TZ")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = f'https://{STORAGE_DOMAIN}/'

STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_DIRS = [
    BASE_DIR / 'storage',
]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_URL = f'https://{MEDIA_DOMAIN}/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth user model
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-user-model

AUTH_USER_MODEL = 'account.Account'

ADMINS = tuple(parseaddr(email) for email in env.list('ADMINS'))

MANAGERS = tuple(parseaddr(email) for email in env.list('MANAGERS'))


# Superuser
# https://docs.djangoproject.com/en/6.0/ref/django-admin/#createsuperuser

DJANGO_SUPERUSER_PASSWORD = env('DJANGO_SUPERUSER_PASSWORD')

DJANGO_SUPERUSER_EMAIL = env('DJANGO_SUPERUSER_EMAIL')

DJANGO_SUPERUSER_USERNAME = env('DJANGO_SUPERUSER_USERNAME')


# SMTP
# https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-EMAIL_BACKEND

SERVER_EMAIL = env('SERVER_EMAIL')

DEFAULT_FROM_EMAIL = env('SERVER_EMAIL')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = env('EMAIL_HOST')

EMAIL_HOST_USER = DEFAULT_FROM_EMAIL

EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

EMAIL_PORT = env('EMAIL_PORT')

EMAIL_SUBJECT_PREFIX = env('EMAIL_SUBJECT_PREFIX')

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False


# Sites framework
# https://docs.djangoproject.com/en/6.0/ref/contrib/sites/#enabling-the-sites-framework

SITE_ID = 1


# Cross-origin resource sharing
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

CORS_ALLOWED_ORIGIN_REGEXES = [
    rf"^https://(\w+\.)?{SITE_DOMAIN.replace('.', r'\.')}/?$",
    rf"^https://(\w+\.)?workload-dashboard.ru/?$",]

CORS_ALLOW_CREDENTIALS = env("CORS_ALLOW_CREDENTIALS")

CSRF_TRUSTED_ORIGINS = [
    f"https://{SITE_DOMAIN}",
    f"https://*.{SITE_DOMAIN}",
    "https://*.workload-dashboard.ru"
    
    "http://localhost:3000"
]


# CSRF settings
# https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-CSRF_COOKIE_DOMAIN

CSRF_COOKIE_HTTPONLY = env("CSRF_COOKIE_HTTPONLY")
CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE")
CSRF_USE_SESSIONS = env("CSRF_USE_SESSIONS")
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE")
CSRF_COOKIE_DOMAIN = env("CSRF_COOKIE_DOMAIN")


# SESSION settings
# https://docs.djangoproject.com/en/6.0/ref/settings/#sessions

SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE")
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE")
SESSION_COOKIE_DOMAIN = env("SESSION_COOKIE_DOMAIN")


# Celery
# https://docs.celeryq.dev/en/stable/

CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND_URL", default="redis://redis:6379/0")

CELERY_CACHE_BACKEND = env("CELERY_BROKER_URL", default="amqp://avocado:backend@rabbitmq:5672/")

CELERY_TIMEZONE = TIME_ZONE

CELERY_TASK_TRACK_STARTED = env("CELERY_TASK_TRACK_STARTED", default=True)

CELERY_TASK_TIME_LIMIT = env("CELERY_TASK_TIME_LIMIT", default=1800)


# Data upload max limit
# https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-DATA_UPLOAD_MAX_NUMBER_FIELDS

DATA_UPLOAD_MAX_NUMBER_FIELDS = env("DATA_UPLOAD_MAX_NUMBER_FIELDS", default=100000)


# Django Rest Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/

# JWT Environ
JWT_ACCESS_TOKEN_MINUTES = env("JWT_ACCESS_TOKEN_MINUTES")
JWT_REFRESH_TOKEN_DAYS = env("JWT_REFRESH_TOKEN_DAYS")
JWT_ALGORITHM = env("JWT_ALGORITHM")
JWT_AUTH_COOKIE = env("JWT_AUTH_COOKIE")
JWT_AUTH_COOKIE_REFRESH = env("JWT_AUTH_COOKIE_REFRESH")
JWT_AUTH_COOKIE_DOMAIN = env("JWT_AUTH_COOKIE_DOMAIN")
JWT_AUTH_COOKIE_SECURE = env("JWT_AUTH_COOKIE_SECURE")
JWT_AUTH_COOKIE_HTTP_ONLY = env("JWT_AUTH_COOKIE_HTTP_ONLY")
JWT_AUTH_COOKIE_SAMESITE = env("JWT_AUTH_COOKIE_SAMESITE")
JWT_AUTH_COOKIE_PATH = env("JWT_AUTH_COOKIE_PATH")
JWT_ROTATE_REFRESH_TOKENS = env("JWT_ROTATE_REFRESH_TOKENS")
JWT_BLACKLIST_AFTER_ROTATION = env("JWT_BLACKLIST_AFTER_ROTATION")
JWT_UPDATE_LAST_LOGIN = env.bool("JWT_UPDATE_LAST_LOGIN")
JWT_AUTH_HEADER_TYPES = env("JWT_AUTH_HEADER_TYPES")
JWT_AUTH_HEADER_NAME = env("JWT_AUTH_HEADER_NAME")
JWT_USER_ID_FIELD = env("JWT_USER_ID_FIELD")
JWT_USER_ID_CLAIM = env("JWT_USER_ID_CLAIM")
JWT_SLIDING_TOKEN_REFRESH_EXP_CLAIM = env("JWT_SLIDING_TOKEN_REFRESH_EXP_CLAIM")
JWT_SLIDING_TOKEN_MINUTES = env("JWT_SLIDING_TOKEN_MINUTES")
JWT_SLIDING_REFRESH_DAYS = env("JWT_SLIDING_REFRESH_DAYS")


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=JWT_ACCESS_TOKEN_MINUTES),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=JWT_REFRESH_TOKEN_DAYS),
    "ROTATE_REFRESH_TOKENS": JWT_ROTATE_REFRESH_TOKENS,
    "BLACKLIST_AFTER_ROTATION": JWT_BLACKLIST_AFTER_ROTATION,
    "UPDATE_LAST_LOGIN": JWT_UPDATE_LAST_LOGIN,

    "ALGORITHM": JWT_ALGORITHM,
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": tuple(JWT_AUTH_HEADER_TYPES.split(",")),
    "AUTH_HEADER_NAME": JWT_AUTH_HEADER_NAME,
    "USER_ID_FIELD": JWT_USER_ID_FIELD,
    "USER_ID_CLAIM": JWT_USER_ID_CLAIM,
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": JWT_SLIDING_TOKEN_REFRESH_EXP_CLAIM,
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=JWT_SLIDING_TOKEN_MINUTES),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=JWT_SLIDING_REFRESH_DAYS),

    "TOKEN_OBTAIN_SERIALIZER": "api.serializers.MyTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",

    "AUTH_COOKIE": JWT_AUTH_COOKIE,
    "AUTH_COOKIE_REFRESH": JWT_AUTH_COOKIE_REFRESH,
    "AUTH_COOKIE_DOMAIN": JWT_AUTH_COOKIE_DOMAIN,
    "AUTH_COOKIE_SECURE": JWT_AUTH_COOKIE_SECURE,
    "AUTH_COOKIE_HTTP_ONLY": JWT_AUTH_COOKIE_HTTP_ONLY,
    "AUTH_COOKIE_PATH": JWT_AUTH_COOKIE_PATH,
    "AUTH_COOKIE_SAMESITE": JWT_AUTH_COOKIE_SAMESITE,
}


# djoser
# https://djoser.readthedocs.io/en/latest/index.html

DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': env("DJOSER_SEND_ACTIVATION_EMAIL"),
    'SERIALIZERS': {
        'user_create': 'account.serializers.CustomUserCreateSerializer',
        'current_user': 'telegram.serializer.TelegramUserSerializer',
    },
}

# END-TO-END
FIELD_ENCRYPTION_KEY = env("FIELD_ENCRYPTION_KEY")
