# Generated by Django 5.2.9 on 2026-02-21 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSBlacklistedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Номер телефона в нормализованном формате', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79991234567', regex='^\\+\\d{9,15}$')], verbose_name='Номер телефона')),
                ('reason', models.CharField(choices=[('expired_code', 'Код истёк'), ('too_many_attempts', 'Слишком много попыток'), ('too_many_requests', 'Слишком много SMS'), ('invalid_code', 'Неверный код'), ('fraud_suspected', 'Подозрение на мошенничество'), ('manual', 'Ручная блокировка администратором'), ('provider_error', 'Ошибка SMS-провайдера')], default='expired_code', help_text='Причина, по которой номер был заблокирован', max_length=32, verbose_name='Причина блокировки')),
                ('banned_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время применения блокировки', verbose_name='Дата блокировки')),
                ('banned_until', models.DateTimeField(blank=True, help_text='Если не указано — блокировка бессрочная', null=True, verbose_name='Блокировка действует до')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Определяет, действует ли блокировка в данный момент', verbose_name='Активная блокировка')),
            ],
            options={
                'verbose_name': 'Телефон в чёрном списке',
                'verbose_name_plural': 'Чёрный список телефонов',
                'indexes': [models.Index(fields=['phone_number', 'is_active'], name='sms_provide_phone_n_401116_idx'), models.Index(fields=['is_active', 'banned_until'], name='sms_provide_is_acti_c3154b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main SMS Provider', max_length=100, verbose_name='Название настройки')),
                ('provider', models.CharField(choices=[('smsc', 'SMSC.ru')], default='smsc', max_length=50, verbose_name='SMS-провайдер')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Должна быть активна только одна запись', verbose_name='Активная настройка')),
                ('login', models.CharField(blank=True, help_text='Логин для авторизации у SMS-провайдера', max_length=255, null=True, verbose_name='Логин')),
                ('password', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Пароль или API-ключ для авторизации у SMS-провайдера', max_length=255, null=True, verbose_name='Пароль'))),
                ('sender_id', models.CharField(blank=True, help_text='Имя/подпись отправителя (если поддерживается провайдером)', max_length=50, null=True, verbose_name='Имя отправителя')),
                ('code_ttl_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время жизни кода (мин)')),
                ('code_length', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(4)], verbose_name='Длина SMS-кода')),
                ('max_verify_attempts', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум попыток ввода кода')),
                ('resend_cooldown_seconds', models.PositiveIntegerField(default=90, help_text='Минимальный интервал между запросами кода для одного телефона', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал повторной отправки (сек)')),
                ('max_sends_per_day', models.PositiveIntegerField(default=5, help_text='Сколько раз можно запросить SMS за 24 часа на один телефон', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Лимит SMS в сутки')),
                ('ban_minutes_after_daily_limit', models.PositiveIntegerField(default=1440, help_text='На сколько минут банить номер при превышении суточного лимита', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Бан при превышении лимита (мин)')),
                ('blacklist_after_expired', models.BooleanField(default=True, help_text='Если включено — номер попадёт в blacklist, если код истёк и не был использован', verbose_name='Банить при истечении кода')),
                ('blacklist_duration_minutes', models.PositiveIntegerField(default=1440, help_text='На сколько минут банить номер (0 — навсегда)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длительность бана (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка SMS провайдера',
                'verbose_name_plural': 'Настройки SMS провайдеров',
                'indexes': [models.Index(fields=['is_active', 'provider'], name='sms_provide_is_acti_25722d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_sms_provider_settings')],
            },
        ),
        migrations.CreateModel(
            name='SMSAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Номер телефона в нормализованном формате', max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +79991234567', regex='^\\+\\d{9,15}$')], verbose_name='Номер телефона')),
                ('code_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 от кода (сам код не хранится)', max_length=64, verbose_name='Хеш кода')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('used', 'Использован'), ('expired', 'Истёк'), ('blocked', 'Заблокирован')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Дата и время окончания действия кода', verbose_name='Действителен до')),
                ('verify_attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток ввода')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='Максимум попыток')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('meta', models.JSONField(blank=True, help_text='Ответ провайдера, message_id и т.п.', null=True, verbose_name='Метаданные')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='sms_provider.smsprovidersettings', verbose_name='Настройка провайдера')),
            ],
            options={
                'verbose_name': 'SMS-код доступа',
                'verbose_name_plural': 'SMS-коды доступа',
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='sms_provide_phone_n_1a4ff1_idx'), models.Index(fields=['phone_number', 'status', 'expires_at'], name='sms_provide_phone_n_cfefcd_idx'), models.Index(fields=['created_at'], name='sms_provide_created_cd20a3_idx')],
            },
        ),
    ]
