# Generated by Django 5.2.9 on 2026-02-21 12:45

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO-код языка (ru, en, es и т.д.)', max_length=10, unique=True, verbose_name='Код языка')),
                ('name', models.CharField(help_text='Название языка', max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(blank=True, help_text='Флаг или эмодзи языка', max_length=5, verbose_name='Эмодзи')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен для выбора пользователями', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код региона (us, eu, asia и т.д.)', max_length=20, unique=True, verbose_name='Код региона')),
                ('name', models.CharField(help_text='Название региона', max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(blank=True, help_text='Флаг или эмодзи региона', max_length=5, verbose_name='Эмодзи')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен для выбора пользователями', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название часового пояса (UTC+3, Europe/Moscow и т.д.)', max_length=50, unique=True, verbose_name='Название')),
                ('offset', models.IntegerField(help_text='Смещение относительно UTC в минутах', verbose_name='Смещение UTC')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен для выбора пользователями', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Часовой пояс',
                'verbose_name_plural': 'Часовые пояса',
                'ordering': ('offset',),
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.CharField(max_length=512, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='telegram.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История входов пользователя',
                'verbose_name_plural': 'Истории входов пользователей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта пользователя', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='user', help_text='Роль пользователя в системе', max_length=20, verbose_name='Роль')),
                ('username', models.CharField(blank=True, help_text='Telegram-имя пользователя', max_length=255, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя из Telegram', max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя из Telegram', max_length=255, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона пользователя', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')], verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, help_text='Аватарка пользователя', null=True, upload_to='avatars/', verbose_name='Аватарка')),
                ('consent_accepted', models.BooleanField(default=False, help_text='Пользователь дал согласие на обработку персональных данных', verbose_name='Согласие на обработку ПДн')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время первого взаимодействия с ботом', verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Дата и время последнего действия пользователя', verbose_name='Последняя активность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('telegram', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='telegram.telegramuser', verbose_name='Telegram аккаунт')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.language', verbose_name='Язык')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.region', verbose_name='Регион')),
                ('timezone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.timezone', verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ('-registration_date',),
                'indexes': [models.Index(fields=['email'], name='account_acc_email_ddd6d0_idx'), models.Index(fields=['role'], name='account_acc_role_9e7c6a_idx'), models.Index(fields=['region'], name='account_acc_region__a45a26_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
