# Generated by Django 5.2.9 on 2026-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Публичный ключ'),
        ),
    ]
