# Generated by Django 5.2.9 on 2026-02-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_public_key'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
