# Generated by Django 5.2.9 on 2026-03-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hide_last_seen',
            field=models.BooleanField(default=False, verbose_name='Скрыть время последнего визита'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний визит'),
        ),
    ]
